name: secret_santa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.4
  image: ^4.2.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: PermanentMarker
      fonts:
        - asset: assets/fonts/PermanentMarker/PermanentMarker-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-100.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/static/Montserrat-200.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/static/Montserrat-300.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/static/Montserrat-400.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/static/Montserrat-500.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/static/Montserrat-600.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/static/Montserrat-700.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/static/Montserrat-800.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/static/Montserrat-900.ttf
          weight: 900

